version: '3'
services:
        web:
                image: fr0st_v1
                build: .
                ports:
                        - "8045:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/p4t5_fr0st/volumes
